Add Kamon logback
BlueBrain/nexus-service pull request #7
Opened 2018-02-23 11:24 UTC by hygt

2018-02-23 12:14 UTC, umbreak submitted a review, later dismissed

2018-02-23 12:53 UTC, bogdanromanx requested changes

2018-02-23 12:53 UTC, bogdanromanx commented on build.sbt
> +                                kamonLogback,
could we have this dependency at `Runtime`? I don't think we depend at compile.

2018-02-26 04:55 UTC, bogdanromanx approved these changes

2018-02-26 10:56 UTC, merged