Added TraceDirectives to enable request entity tracing
BlueBrain/nexus-service pull request #9
Opened 2018-03-06 23:17 UTC by bogdanromanx

2018-03-07 09:10 UTC, umbreak submitted a review, later dismissed

2018-03-07 10:53 UTC, hygt requested changes

2018-03-07 10:53 UTC, hygt commented on Jenkinsfile
> +                            sh 'sbt clean scalafmtCheck scalafmtSbtCheck scapegoat'
Both `scalafmtCheck` and `scalafmtSbtCheck` ?

2018-03-07 10:53 UTC, hygt commented on modules/indexing/src/main/scala/ch/epfl/bluebrain/nexus/service/indexer/persistence/SequentialTagIndexer.scala
> +          println(s"Offset $offset"); projection.storeLatestOffset(offset)
Can we remove this `;` ?

2018-03-09 09:10 UTC, hygt approved these changes

2018-03-09 09:11 UTC, merged